language: julia

os:
    - linux

julia:
    - 1.2
    - 1.3
    - nightly

matrix:
    allow_failures:
        - julia: nightly

after_success:
    - julia -e 'cd(Pkg.dir("FEMBeam")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
