language: julia

os:
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

matrix:
    allow_failures:
        - julia: 1.0
        - julia: nightly

after_success:
    - julia -e 'cd(Pkg.dir("FEMBeam")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
